version: '3'

services:
  fort-dev:
    image: fort-dev
    build: .

  py-build:
    image: fort-dev
    command: ["setup.py", "bdist_wheel"]

  twine-upload:
    image: fort-dev
    entrypoint: ["twine"]
    command: ["upload", "--skip-existing", "--verbose", "dist/*"]
    environment:
      TWINE_PASSWORD:
      TWINE_USERNAME:

  cleanup:
    image: fort-dev
    entrypoint: ["rm", "-rf", "build", "dist", "fort.egg-info"]
