[build-system]
build-backend = "uv_build"
requires = ["uv-build>=0.11.16,<0.12.0"]

[project]
name = "fort"
version = "2026.0"
description = "The Python database micropackage"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[[project.authors]]
name = "William Jackson"
email = "william@subtlecoolness.com"

[project.urls]
"Homepage" = "https://github.com/williamjacksn/fort"
"Issues" = "https://github.com/williamjacksn/fort/issues"

[dependency-groups]
dev = [
    "psycopg2-binary>=2.9.12",
    "ruff>=0.15.14",
    "ty>=0.0.40",
    "uv-build>=0.11.16",
]

[tool.ruff.lint]
select = ["ANN", "E", "F", "FURB", "I", "PERF", "RUF", "S", "UP"]
