[project]
name = "fort"
version = "2026.0"
description = "The Python database micropackage"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[[project.authors]]
name = "William Jackson"
email = "william@subtlecoolness.com"

[project.urls]
"Homepage" = "https://github.com/williamjacksn/fort"
"Issues" = "https://github.com/williamjacksn/fort/issues"

[build-system]
build-backend = "uv_build"
requires = ["uv-build>=0.12.1,<0.13.0"]

[dependency-groups]
dev = [
    "psycopg2-binary>=2.9.12",
    "ruff>=0.16.5",
    "ty>=0.0.66",
    "uv-build>=0.12.1",
]

[tool.ruff.lint]
extend-select = ["ANN", "E", "F", "FURB", "I", "PERF", "Q", "RSE", "RUF", "S", "UP"]
