name: Build the helper image

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:

  build:
    name: Build the helper image
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repository
        uses: actions/checkout@v2.3.4

      - name: Build the image
        uses: docker/build-push-action@v1.1.0
        with:
          repository: fort-dev

      - name: Tag and push the image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v1.1.0
        with:
          repository: ${{ github.repository_owner }}/fort-dev
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
          tag_with_ref: true
          add_git_labels: true
