name: Publish the release package to PyPI

on:
  release:
    types:
      - published

jobs:

  publish:
    name: Publish the release package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
      - name: Build the package
        run: docker-compose run --user="$(id -u):$(id -g)" -T py-build
      - name: Publish the package to PyPI
        run: docker-compose run -T twine-upload
        env:
          TWINE_PASSWORD: ${{ secrets.twine_password }}
          TWINE_USERNAME: ${{ secrets.twine_username }}
      - name: Get file names
        id: files
        run: |
          echo "SDIST=$(cd dist && ls *.gz)" >> $GITHUB_OUTPUT
          echo "WHEEL=$(cd dist && ls *.whl)" >> $GITHUB_OUTPUT
      - name: Upload sdist to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_content_type: application/octet-stream
          asset_path: ${{ github.workspace }}/dist/${{ steps.files.outputs.SDIST }}
          asset_name: ${{ steps.files.outputs.SDIST }}
          upload_url: ${{ github.event.release.upload_url }}
      - name: Upload wheel to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_content_type: application/octet-stream
          asset_path: ${{ github.workspace }}/dist/${{ steps.files.outputs.WHEEL }}
          asset_name: ${{ steps.files.outputs.WHEEL }}
          upload_url: ${{ github.event.release.upload_url }}
